def configure(conf):
    conf.check_cxx(fragment="""
                            #define BOOST_TEST_MODULE Config test\n
    			    #include <boost/test/unit_test.hpp>\n
                            int main() {}
                            """, msg = 'Checking for boost unit testing library', lib = 'boost_unit_test_framework', uselib_store = 'BOOST_TEST')

def build(bld):
    obj = bld(features='cxx cxxprogram')
    obj.name   = 'unit-tests'
    obj.uselib =  'BOOST_TEST'
    obj.use    = 'libdcpomatic2'
    obj.source = """
                 ../src/rule.cc
                 ../src/util.cc
                 rule_test.cc
                 test.cc
                 """
    obj.target = 'unit-tests'
    obj.install_path = ''
