def build(bld):
    obj = bld(features='cxx cxxprogram')
    obj.name   = 'unit-tests'
    obj.uselib =  'BOOST_TEST BOOST_SYSTEM'
    obj.use    = 'libdcpomatic2'
    obj.source = """
                 ../src/config.cc
                 ../src/datum.cc
                 ../src/json_node.cc
                 ../src/rule.cc
                 ../src/toast_socket.cc
                 ../src/util.cc
                 rule_test.cc
                 json_node_test.cc
                 test.cc
                 """
    obj.target = 'unit-tests'
    obj.install_path = ''
