#!/bin/bash
for f in launcher fan; do
	inkscape -y 0 -z -f $f.svg --export-png ../app/src/main/res/drawable-mdpi/ic_$f.png --export-width=48 --export-height=48 --export-area-page
	inkscape -y 0 -z -f $f.svg --export-png ../app/src/main/res/drawable-hdpi/ic_$f.png --export-width=72 --export-height=72 --export-area-page
	inkscape -y 0 -z -f $f.svg --export-png ../app/src/main/res/drawable-xhdpi/ic_$f.png --export-width=96 --export-height=96 --export-area-page
	inkscape -y 0 -z -f $f.svg --export-png ../app/src/main/res/drawable-xxhdpi/ic_$f.png --export-width=144 --export-height=144 --export-area-page
done
