#define OP_SEND_BASIC 0
#define OP_SEND_ALL 1

#define OP_CHANGE 0x10
#define OP_HEATING_ENABLED (OP_CHANGE | 0)
#define OP_ZONE_HEATING_ENABLED (OP_CHANGE | 1)
#define OP_TARGET (OP_CHANGE | 2)
#define OP_BOILER_ON (OP_CHANGE | 3)
#define OP_TEMPERATURES (OP_CHANGE | 4)
#define OP_HUMIDITIES (OP_CHANGE | 5)
#define OP_RULES (OP_CHANGE | 6)
#define OP_ACTUATORS (OP_CHANGE | 7)
#define OP_ALL (OP_CHANGE | 0xf)
