sources = """
          broadcast_listener.cc
          control_server.cc
          datum.cc
          esp8266_node.cc
          json_node.cc
          node.cc
          rule.cc
          sensor.cc
          server.cc
          state.cc
          toast_socket.cc
          toastd.cc
          util.cc
          """

def build(bld):
    obj = bld(features='cxx cxxprogram')
    obj.name = 'toastd'
    obj.target = 'toastd'
    obj.uselib = 'BOOST_SYSTEM'
    obj.source = sources
